apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: atlas-commerce
data:
  NODE_ENV: "production"
  BACKEND_PORT: "5000"           
  FRONTEND_PORT: "5173"          
  REDIS_URL: "redis://redis-service:6379"
  NEXT_PUBLIC_API_URL: "http://backend-service:5000"  