apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlas-commerce

resources:
  - ConfigMap.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - nginx-ingress.yaml
  - secret-dev.yaml