apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: atlas-commerce
type: Opaque
stringData:
  MONGO_URI: ""
  STRIPE_SECRET_KEY: ""
  STRIPE_PUBLIC_KEY: ""

  JWT_SECRET: ""
