apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: atlas-commerce
type: Opaque
stringData:
  MONGO_URI: "mongodb://localhost:27017/atlas-commerce-dev"
  STRIPE_SECRET_KEY: "sk_test_dummykey123"
  STRIPE_PUBLIC_KEY: "pk_test_dummypublic456"
  JWT_SECRET: "dummy-jwt-secret-for-dev-only"